In [36]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.interpolate import interp1d

In [37]:
violencia_a = pd.read_csv('denuncias_mensuales.csv')

In [38]:
violencia_a

Unnamed: 0  index  anio         mes  denuncias_mes
0            0      3  2016       Enero           1315
1            1      4  2016     Febrero           1533
2            2      7  2016       Marzo           1541
3            3      0  2016       Abril           1739
4            4      8  2016        Mayo           1844
5            5      6  2016       Junio           1780
6            6      5  2016       Julio           1434
7            7      1  2016      Agosto           1601
8            8     11  2016  Septiembre           1521
9            9     10  2016     Octubre           1532
10          10      9  2016   Noviembre           1334
11          11      2  2016   Diciembre           1384
12          12     15  2017       Enero           1387
13          13     16  2017     Febrero           1346
14          14     19  2017       Marzo           1584
15          15     12  2017       Abril           1511
16          16     20  2017        Mayo           1659
17          17     18  2017       Junio           1712
18          18     17  2017       Julio           1490
19          19     13  2017      Agosto           1697
20          20     23  2017  Septiembre           1561
21          21     22  2017     Octubre           1611
22          22     21  2017   Noviembre           1447
23          23     14  2017   Diciembre           1430
24          24     27  2018       Enero           1449
25          25     28  2018     Febrero           1532
26          26     31  2018       Marzo           1769
27          27     24  2018       Abril           1877
28          28     32  2018        Mayo           1892
29          29     30  2018       Junio           1655
30          30     29  2018       Julio           1745
31          31     25  2018      Agosto           1582
32          32     35  2018  Septiembre           1673
33          33     34  2018     Octubre           1676
34          34     33  2018   Noviembre           1570
35          35     26  2018   Diciembre           1513
36          36     39  2019       Enero           1609
37          37     40  2019     Febrero           1754
38          38     43  2019       Marzo           2205
39          39     36  2019       Abril           2171
40          40     44  2019        Mayo           2477
41          41     42  2019       Junio           2156
42          42     41  2019       Julio           2206
43          43     37  2019      Agosto           2402
44          44     47  2019  Septiembre           2315
45          45     46  2019     Octubre           2193
46          46     45  2019   Noviembre           2114
47          47     38  2019   Diciembre           2174
48          48     49  2020       Enero           2064
49          49     50  2020     Febrero           2482
50          50     51  2020       Marzo           2792
51          51     48  2020       Abril           1786
52          52     52  2020        Mayo           1550

In [39]:
del violencia_a['index']

In [40]:
del violencia_a['anio']

In [41]:
del violencia_a['mes']

In [42]:
violencia_a

Unnamed: 0  denuncias_mes
0            0           1315
1            1           1533
2            2           1541
3            3           1739
4            4           1844
5            5           1780
6            6           1434
7            7           1601
8            8           1521
9            9           1532
10          10           1334
11          11           1384
12          12           1387
13          13           1346
14          14           1584
15          15           1511
16          16           1659
17          17           1712
18          18           1490
19          19           1697
20          20           1561
21          21           1611
22          22           1447
23          23           1430
24          24           1449
25          25           1532
26          26           1769
27          27           1877
28          28           1892
29          29           1655
30          30           1745
31          31           1582
32          32           1673
33          33           1676
34          34           1570
35          35           1513
36          36           1609
37          37           1754
38          38           2205
39          39           2171
40          40           2477
41          41           2156
42          42           2206
43          43           2402
44          44           2315
45          45           2193
46          46           2114
47          47           2174
48          48           2064
49          49           2482
50          50           2792
51          51           1786
52          52           1550

In [43]:
arr = violencia_a.to_numpy()

In [44]:
arr

array([[   0, 1315],
       [   1, 1533],
       [   2, 1541],
       [   3, 1739],
       [   4, 1844],
       [   5, 1780],
       [   6, 1434],
       [   7, 1601],
       [   8, 1521],
       [   9, 1532],
       [  10, 1334],
       [  11, 1384],
       [  12, 1387],
       [  13, 1346],
       [  14, 1584],
       [  15, 1511],
       [  16, 1659],
       [  17, 1712],
       [  18, 1490],
       [  19, 1697],
       [  20, 1561],
       [  21, 1611],
       [  22, 1447],
       [  23, 1430],
       [  24, 1449],
       [  25, 1532],
       [  26, 1769],
       [  27, 1877],
       [  28, 1892],
       [  29, 1655],
       [  30, 1745],
       [  31, 1582],
       [  32, 1673],
       [  33, 1676],
       [  34, 1570],
       [  35, 1513],
       [  36, 1609],
       [  37, 1754],
       [  38, 2205],
       [  39, 2171],
       [  40, 2477],
       [  41, 2156],
       [  42, 2206],
       [  43, 2402],
       [  44, 2315],
       [  45, 2193],
       [  46, 2114],
       [  47,

In [45]:
y = arr[:,1]

In [46]:
y

array([1315, 1533, 1541, 1739, 1844, 1780, 1434, 1601, 1521, 1532, 1334,
       1384, 1387, 1346, 1584, 1511, 1659, 1712, 1490, 1697, 1561, 1611,
       1447, 1430, 1449, 1532, 1769, 1877, 1892, 1655, 1745, 1582, 1673,
       1676, 1570, 1513, 1609, 1754, 2205, 2171, 2477, 2156, 2206, 2402,
       2315, 2193, 2114, 2174, 2064, 2482, 2792, 1786, 1550])

In [47]:
x = arr[:,0]

In [48]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52])

In [49]:
coefficients1 = np.polyfit(x, y, 1, full=True)